site_name: "Skywalker: A Parameter Study Tool for Box Models"

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.sections
#    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
